### ISSUE TITLE
Make Post model/table

### ISSUE THREAD

**Issue by d1vyanshu** [pclubiitk/Campus-Discuss-Backend#2]

**Comment by SomTambe** [comment]
@aniketkar1 and I have chosen this. Please assign this to us.

**Comment by shubh10** [comment]
I am also in there team

**Comment by namangup** [comment]
@SomTambe Please comment the name of your app and model .

**Comment by shubh10** [comment]
App name  - posts
model name  - Post

**Comment by shubh10** [comment]
App name - posts
Model name - Posts
