### ISSUE TITLE
Write an API to set password using email link

### ISSUE THREAD

**Issue by vikrantmalik051** [pclubiitk/Campus-Discuss-Backend#35]
References: 
https://docs.djangoproject.com/en/3.0/topics/auth/passwords/
                     https://pypi.org/project/bcrypt/#password-hashing

**Comment by aashishpiitk** [comment]
i m taking this

**Comment by aashishpiitk** [comment]
tests ke liye alag se folder banan hai kya

if i have a tests folder inside users folder and a test file is located inside this folder then how can i import the User from models.py of users to my tests.py file inside the tests folder
