### ISSUE TITLE
Write an API to fetch posts by author

### ISSUE THREAD

**Issue by d1vyanshu** [pclubiitk/Campus-Discuss-Backend#60]
To display all the posts created by any user. You can refer to life-iitk/Lifeiitkbackend#67 for help. Remember using serializer to return posts in JSON format

**Comment by aashishpiitk** [comment]
I'm doing this

**Comment by d1vyanshu** [comment]
@aashishpiitk  We have the api to fetch post by streams added now. You can have a look at it for help. When can you finish this?

**Comment by aashishpiitk** [comment]
I will finish it by tomorrow
