### ISSUE TITLE
Write a task to send notifications to the user

### ISSUE THREAD

**Issue by vikrantmalik051** [pclubiitk/Campus-Discuss-Backend#77]
Reference: https://github.com/V1krant/Lifeiitkbackend/commit/ff1f63ebaafb25d4da618c4f03294878f7770547

**Comment by aashishpiitk** [comment]
I'm working on it

**Comment by aashishpiitk** [comment]
Please someone take this issue ,I'm not able to work on it anymore

**Comment by SomTambe** [comment]
@d1vyanshu I am taking this issue, kindly note.
