### ISSUE TITLE
Make Bookmarks Model/Table

### ISSUE THREAD

**Issue by vikrantmalik051** [pclubiitk/Campus-Discuss-Backend#8]

**Comment by SarthakRout** [comment]
I and @pramodh-1612 would like to work on this issue.

**Comment by InvincibleKnight** [comment]
> I and @pramodh-1612 would like to work on this issue.

Could you please tell the app name and the model name.

Thanks.

**Comment by SarthakRout** [comment]
> > I and @pramodh-1612 would like to work on this issue.
> 
> Could you please tell the app name and the model name.
> 
> Thanks.

App name - Bookmark
Model name - Bookmark
